### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Svelsien** [bepvte/bd-addons#1]
Doesn't work,
Gifs aren't saved in the plugin folder.

**Comment by bepvte** [comment]
Hi! The gifs arent saved, but a list of the gifs is. Check for "gifbackup.json" in your plugins folder after enabling the plugin. That backup file will restore your favorite gifs list if it ever gets wiped by a discord update.

**Comment by Svelsien** [comment]
yep it's there.
tested it and works fine
thanks
