### ISSUE TITLE
Fix StereoSound

### ISSUE THREAD

**Issue by bepvte** [bepvte/bd-addons#12]
Its in bad shape.

**Comment by 8bit-coder** [comment]
Does this plugin still work? Or is it entirely broken?

**Comment by vicsEND** [comment]
when will stereo be fixed?

**Comment by SenpaiAnimeBaka** [comment]
any plans on updating the plugin?

**Comment by bepvte** [comment]
I cannot find what is breaking the plugin. I do not know how to fix it, sorry.
