### ISSUE TITLE
Stereo Audio

### ISSUE THREAD

**Issue by jacklollz2** [bepvte/bd-addons#13]
Stereo audio may be broken because echo cancellation is forced on.
https://www.reddit.com/r/discordapp/comments/nsb2y1/psa_echo_cancellation_seems_to_be_forced_on_with/
Stereo is my most desired for feature, please keep it functioning, it's implicitly valuable to me.

**Comment by bepvte** [comment]
Its very hard for me to figure out what has broken it, discords audio system is very opaque and is usually native code. I do what I can but I dont really ever know, and I also dont even have a stereo mic to test it with so I depend on others. See #12

**Comment by vantiss** [comment]
I and my partner both have stereo mics, if you need any help testing. We're also both familiar with CodeStuff™ and I've done a lot of testing for zerebos, so I'd be happy to give you a hand with this if you'd like! Happy to give you my discord handle or other info privately if you decide you're interested. We made use of this plugin all the time and have really missed it :(

**Comment by vantiss** [comment]
> Its very hard for me to figure out what has broken it, discords audio system is very opaque and is usually native code. I do what I can but I dont really ever know, and I also dont even have a stereo mic to test it with so I depend on others. See #12

I and my partner both have stereo mics, if you need any help testing. We're also both familiar with CodeStuff™ and I've done a lot of testing for zerebos, so I'd be happy to give you a hand with this if you'd like! Happy to give you my discord handle or other info privately if you decide you're interested. We made use of this plugin all the time and have really missed it :(

**Comment by bepvte** [comment]
I don't know how to fix it, sorry. I believe the mumble voice app has good stereo support.
