### ISSUE TITLE
i have an old gifbackup.json file but i can't recover my old gif's

### ISSUE THREAD

**Issue by LweoIsHere** [bepvte/bd-addons#17]
so basically, i was trying to recover my old gif's and i can't. i had this file in my old windows backup so is there anyway of trying to recover all of the gif's that i had in the past?

here's my gifbackup file:

*deleted massive gif list*

**Comment by bepvte** [comment]
There are two ways you can do it! Please delete the giant gif list so i can scroll down this issue though.

## Method 1:
Install this [ancient version of gifsaver](https://raw.githubusercontent.com/bepvte/bd-addons/62359aae57d37861094d57a807e23ba792e5de7e/plugins/gifsaver.plugin.js) by pressing ctrl s and putting it in plugins folder of betterdiscord. Then place that gifbackup.json in the plugins folder next to it. Start discord, and ignore the update request until you are sure your gifs have been restored. Then you can update gifsaver once you are confident its working.

## Method 2 (Fallback/no betterdiscord)

1. Disable gifsaver if its enabled until this is done
2. Open inspect element with ctrl shift i (this works in the desktop app)
3. Click the tab that says "Application"
4. Click local storage on the left
5. In the filter bar type giffavorite
6. Double click the right column of GifFavoritesStore
7. Paste in the thing you pasted above
