### ISSUE TITLE
GIFs gone if added after re-login.

### ISSUE THREAD

**Issue by TheGameratorT** [bepvte/bd-addons#2]
So I have this issue that I share my computer with my brother and we are constantly logging out and in to switch accounts.
With this I noticed that if I log out, then log back in and favorite a GIF, all of my GIFs disappear forever.

I think that the solution would be to save different GIF data per user and force a restore after a login.

**Comment by bepvte** [comment]
I know that for many people they prefer to use multiple accounts with one gifstore, myself included. I recommend you install the discord beta at the bottom of this page: https://discord.com/download. It runs as a separate app then the main version, with its own accounts and everything. I do not recommend using gifsaver on both at once though!!!

Also, dont favorite a gif if you havent restored. It overwrites. It asks to restore after you log in, and it also asks when your gif favorites are empty when you load the plugin, so you can reload it to try to force that.

**Comment by TheGameratorT** [comment]
Yeah...
But I prefer having it automated so I made some upgrades.
I had to remake the code base because I had no idea how to raw patch.
#3
