### ISSUE TITLE
StereoSound

### ISSUE THREAD

**Issue by jacklollz2** [bepvte/bd-addons#22]
Hey, there's a problem with StereoSound, you decided to keep it on your page and link to a YouTube video because you're a bad developer and can't make basic features work.
Could you add stereo audio to Discord?

**Comment by bepvte** [comment]
you are being mean :/

**Comment by bepvte** [comment]
ill get started on that right away thanks for the feed back

**Comment by l0c4lh057** [comment]
I wish I'd get such encouraging feedback too

**Comment by christiankek** [comment]
oimg jacklollz2 your my favorite packer!1!!11!

**Comment by bepvte** [comment]
> oimg jacklollz2 your my favorite packer!1!!11!

no packers are allowed to interact with me ever under any circumstances worst people ive ever dealt with goodbye
