### ISSUE TITLE
GifSaver

### ISSUE THREAD

**Issue by master3395** [bepvte/bd-addons#23]
When you want to put one gif as a favorite on the right side of the box, The favorite button is outside of the frame.

![bilde](https://user-images.githubusercontent.com/4199669/140509175-24b19fe2-8659-4510-8053-1b3dc012d362.png)

**Comment by bepvte** [comment]
Are you sure this issue is gifsaver related, and not caused by discord or mediasaver?

**Comment by master3395** [comment]
My fault, i think it's related to https://github.com/Dastan21/BDAddons/tree/main/plugins/FavoriteMedia
