### ISSUE TITLE
Gifsaver causes BD to crash

### ISSUE THREAD

**Issue by sighofrelief** [bepvte/bd-addons#25]
tin says everything.

**Comment by bepvte** [comment]
Its not gifsaver, its the BD emote system
![image](https://user-images.githubusercontent.com/8226605/141399922-16d44d20-9348-4b35-be5a-971423714de8.png)
Or its another plugin. I have thoroughly tested all versions on latest discord. They dont work, but they dont crash.

**Comment by NotOnii** [comment]
I've also just started getting the same thing. Even after restarting BD without the plugin enabled, it crashes when I open the GIF widget.

**Comment by bepvte** [comment]
Did you read what I said above? Its caused by a different plugin or the emote system, which you have to disable like in the screenshot

**Comment by NotOnii** [comment]
> Did you read what I said above? Its caused by a different plugin or the emote system, which you have to disable like in the screenshot

I already edited my comment to that. I don't use any other plugins (except for a message logger), which I've disabled

**Comment by bepvte** [comment]
Did you disable the emote system like in the screenshot? Its on by default. Also make sure to restart discord completely.

**Comment by NotOnii** [comment]
Yessir, I did

**Comment by NotOnii** [comment]
I also restarted my PC in case there were some background processes or some shit

**Comment by bepvte** [comment]
Ask in bd support server
