### ISSUE TITLE
NoPause

### ISSUE THREAD

**Issue by kilo3421** [bepvte/bd-addons#30]
Hello! I had a wierd issue with spotify, it will pause randomly at the beggening of some musics. The song that gets paused can't be played until skipped and come back. It shows 0 secondes or 3 seconds and then stops, while still displaying the Playing. The issue is only on my computer, which have the plug-in. Its been a week since i had better discord that crashed and thus without any plug-ins and it won't pause anymore. I have no idea how to recreate this, because its random. I did re-install spotify multiples times and used the windows spotify instead of the stand alone. All did the same.

might be usefull information
Windows 10 up to date
Spotify stand alone up to date
better discord up to date

**Comment by bepvte** [comment]
Is this issue related to my plugins? Until you can confirm it doesn't occur without my plugins, I am not the guy to ask. Try spotify support.
