### ISSUE TITLE
CanaryLinks: Threads keep their Canary links

### ISSUE THREAD

**Issue by TheEeveeLovers** [bepvte/bd-addons#32]
How reproduce:
1. Open the Canary or PTB build of Discord.
2. Go to a server where you can make a thread.
3. Make a thread or find an existing one.
4. Right click the thread in the channel list, then click "Copy Link"
5. Paste the link somewhere and notice that the link is a canary link.

**Comment by bepvte** [comment]
Thank you for the report, I'll fix it when the semester ends, im very busy atm!

@SnoozeThis wait for two weeks -> assign to @bepvte, remove label "snoozed"

**Comment by SnoozeThis** [comment]
invalid duration: not a number: two

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/b0KUicDJqM4) I will wait until Thu, 05 May 2022 01:27:21 UTC and then assign to bepvte and remove label snoozed.

**Comment by SnoozeThis** [comment]
Resolved.
