### ISSUE TITLE
Not working as of 22-Aug-2022

### ISSUE THREAD

**Issue by WildFyr16** [bepvte/bd-addons#34]
The plugin "NoSpotifyPause" seems to not be working currently. I am assuming Discord changed something with how it talks with the Spotify API.

**Comment by GitHababi** [comment]
Something that might be helpful for the dev is that at this line:
![image](https://user-images.githubusercontent.com/76075036/192664265-175b529f-36f1-4d40-954c-9403cbefc60d.png)
that prop has changed i think

**Comment by bepvte** [comment]
All my plugins are broken until BetterDiscord releases new features that make it easier to overwrite function modules

**Comment by bepvte** [comment]
Hit the ✅ on this if it works
