### ISSUE TITLE
issues i got into

### ISSUE THREAD

**Issue by Jorep2** [bepvte/bd-addons#35]
it wont let me copy paste (i had to ctrl+v) or accept friend requests. i had to turn off my plugins one by one to track which is the problematic xD. im not code writer just created a profile here to write the issue down xD hope it helps

**Comment by bepvte** [comment]
Let me know if the issue still occurs, discord had a bug for a few hours earlier where pasting did not work for anyone regardless of plugins, so it should have fixed itself

**Comment by Jorep2** [comment]
I still cannot copy paste with mouse options and interact with friend requests. Since i didnt have any other friend request i tried to unblock an account of someone i had blocked and i cannot unblock him. When i disable the plugin everything works normaly. Im sure it is plugin's fault but i dont know if it is 100% its fault since we are talking about software and might interact with something else i have enabled and thus it reacts this way

**Comment by Jorep2** [comment]
> I still cannot copy paste with mouse options and interact with friend requests. Since i didnt have any other friend request i tried to unblock an account of someone i had blocked and i cannot unblock him. When i disable the plugin everything works normaly. Im sure it is plugin's fault but i dont know if it is 100% its fault since we are talking about software and might interact with something else i have enabled and thus it reacts this way

i still had the problem when disabled the plugin so i had the enlightment to close and open the discord to "maybe update itself" since u told me it had a bug by its own. After that i checked again and it seems to work normaly now. Sorry for the extra stress xD
