### ISSUE TITLE
NoSpotifyPause Popup

### ISSUE THREAD

**Issue by AstragoDE** [bepvte/bd-addons#37]
**Plugin name and version**
NoSpotifyPause @ 0.0.3

**Describe the bug**
Although the plugin prevents discord from pausing Spotify, I still get the following banner after 30 seconds. 
![image](https://user-images.githubusercontent.com/51675359/210758632-d9efe673-0f6d-4408-a7c4-46e6b613452e.png)

**Environment**

- Discord Stable
- BetterDiscord
- Plugin tested

**Comment by bepvte** [comment]
The banner is harder to remove then the pause, I just take it as a symbol that the plugin is working. If its really annoying you can hide it with css `:has` and match the spotify logo
