### ISSUE TITLE
[question] spatial audio for discord

### ISSUE THREAD

**Issue by ghzeni** [bepvte/bd-addons#46]
hello bep! I came across your plugin [in this video](https://www.youtube.com/watch?v=yegHLeS_g9k) and even though you mentioned it's broken, seemed to work just fine for me (my friends only heard me speaking from the left side but still, seems like it worked)

I was taking a look at your plugin's code and couldn't help but wonder: **would it be possible to create this, but "reversed"?**

What I mean by that is, instead of stereo-izing your input, doing so for the output. I imagine something like automatically (or manually) assigning everyone to some kind of "seat" in a virtual 3d space and every voice coming from different directions. This would specially be useful for when there's a lot happening (music, multiple people speaking, etc)

I want to take a little look at this, but from the context you've already acquired by doing this, maybe you know if it's impossible to do so straight from the get go? 😄 thanks!

**Comment by bepvte** [comment]
hello,
its easier to do this with the built in discord capability of the RPC server, like is done for that among us spatial voice chat mod.
the capability is here https://discord.com/developers/docs/topics/rpc#setuservoicesettings

**Comment by bepvte** [comment]
also the left side audio thing is the reason why its broken. discord does some internal c++ audio processing built for left channel only thats too much of a pain to fix + everyone who keeps demanding i fix it is really annoying to me about it
