### ISSUE TITLE
Stereo flipped

### ISSUE THREAD

**Issue by Ming842** [bepvte/bd-addons#8]
Hey!

For some reason the stereo is flipped for the plugin, is this a known issue? Or is there something I'm doing wrong here. The audio does go in right, audacity shows the correct channels, but for some reason dicord flips it making left right and right left. 

Greetings, 

Ming!

**Comment by bepvte** [comment]
Are you sure its flipped? Or is it just out of phase? The plugin currently has a bug where audio effects are being applied to the left channel no matter what you do, causing audio quality issues.

**Comment by Ming842** [comment]
Excuse me, I was being stupid. Issue on my part!! Thanks for the quick reply and ofcourse the wonderful plugin though!
